

version: '3.8'
services:
  airflow:
    build: .
    container_name: airflow_sales
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////usr/local/airflow/db/salesanalytics.db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    restart: always
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./data:/usr/local/airflow/data
      - ./db:/usr/local/airflow/db
    command: >
      bash -c "
      airflow db init &&
      airflow user create --username admin --firstname Airflow --lastname Admin --role Admin --email elvo@gmail.com --password admin &&
      airflow scheduler &
      airflow webserver --port 8080
      "
    